// Date: 10/03/2013 9:18:54 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package aussiecraft.client;

import javax.swing.text.html.parser.Entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelKoala extends ModelBase
{
  //fields
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Body1;
    ModelRenderer Nose1;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
  
  public ModelKoala()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(0F, 0F, 0F, 3, 3, 3);
      Leg1.setRotationPoint(-7F, 21F, -5F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(0F, 0F, 0F, 3, 3, 3);
      Leg2.setRotationPoint(-7F, 21F, 2F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(0F, 0F, 0F, 3, 3, 3);
      Leg3.setRotationPoint(0F, 21F, -5F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(0F, 0F, 0F, 3, 3, 3);
      Leg4.setRotationPoint(0F, 21F, 2F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Body1 = new ModelRenderer(this, 0, 0);
      Body1.addBox(0F, 0F, 0F, 10, 6, 14);
      Body1.setRotationPoint(-7F, 15F, -7F);
      Body1.setTextureSize(64, 32);
      Body1.mirror = true;
      setRotation(Body1, 0F, 0F, 0F);
      Nose1 = new ModelRenderer(this, 0, 0);
      Nose1.addBox(0F, 0F, 0F, 2, 2, 1);
      Nose1.setRotationPoint(-3F, 18F, -8F);
      Nose1.setTextureSize(64, 32);
      Nose1.mirror = true;
      setRotation(Nose1, 0F, 0F, 0F);
      Ear1 = new ModelRenderer(this, 0, 0);
      Ear1.addBox(0F, 0F, 0F, 3, 3, 1);
      Ear1.setRotationPoint(2F, 13F, -6F);
      Ear1.setTextureSize(64, 32);
      Ear1.mirror = true;
      setRotation(Ear1, 0F, 0F, 0F);
      Ear2 = new ModelRenderer(this, 0, 0);
      Ear2.addBox(0F, 0F, 0F, 3, 3, 1);
      Ear2.setRotationPoint(-9F, 13F, -5F);
      Ear2.setTextureSize(64, 32);
      Ear2.mirror = true;
      setRotation(Ear2, 0F, 0F, 0F);
  }
  
  public void render(net.minecraft.entity.Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    super.render(par1Entity, par2, par3, par4, par5, par6, par7);
    setRotationAngles(par2, par3, par4, par5, par6, par7);
    Leg1.render(par7);
    Leg2.render(par7);
    Leg3.render(par7);
    Leg4.render(par7);
    Body1.render(par7);
    Nose1.render(par7);
    Ear1.render(par7);
    Ear2.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, null);
  }

}
